#ifndef STRUCTURE_STATE_SPACE_TA_VERIFIER_H
#define STRUCTURE_STATE_SPACE_TA_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef STRUCTURE_STATE_SPACE_TA_READER_H
#include "structure_state_space_ta_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int State_space_ta_DBM_verify_table(flatcc_table_verifier_descriptor_t *td);
static int State_space_ta_Variable_verify_table(flatcc_table_verifier_descriptor_t *td);
static int State_space_ta_State_verify_table(flatcc_table_verifier_descriptor_t *td);
static int State_space_ta_State_transition_verify_table(flatcc_table_verifier_descriptor_t *td);
static int State_space_ta_State_transitions_verify_table(flatcc_table_verifier_descriptor_t *td);
static int State_space_ta_State_space_ta_verify_table(flatcc_table_verifier_descriptor_t *td);

static int State_space_ta_DBM_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* dim */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 0, 4, 4, INT64_C(1073741823)) /* matrice_applatie */)) return ret;
    return flatcc_verify_ok;
}

static inline int State_space_ta_DBM_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_DBM_identifier, &State_space_ta_DBM_verify_table);
}

static inline int State_space_ta_DBM_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_DBM_identifier, &State_space_ta_DBM_verify_table);
}

static inline int State_space_ta_DBM_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_DBM_type_identifier, &State_space_ta_DBM_verify_table);
}

static inline int State_space_ta_DBM_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_DBM_type_identifier, &State_space_ta_DBM_verify_table);
}

static inline int State_space_ta_DBM_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &State_space_ta_DBM_verify_table);
}

static inline int State_space_ta_DBM_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &State_space_ta_DBM_verify_table);
}

static inline int State_space_ta_DBM_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &State_space_ta_DBM_verify_table);
}

static inline int State_space_ta_DBM_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &State_space_ta_DBM_verify_table);
}

static int State_space_ta_Variable_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* v */)) return ret;
    return flatcc_verify_ok;
}

static inline int State_space_ta_Variable_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_Variable_identifier, &State_space_ta_Variable_verify_table);
}

static inline int State_space_ta_Variable_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_Variable_identifier, &State_space_ta_Variable_verify_table);
}

static inline int State_space_ta_Variable_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_Variable_type_identifier, &State_space_ta_Variable_verify_table);
}

static inline int State_space_ta_Variable_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_Variable_type_identifier, &State_space_ta_Variable_verify_table);
}

static inline int State_space_ta_Variable_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &State_space_ta_Variable_verify_table);
}

static inline int State_space_ta_Variable_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &State_space_ta_Variable_verify_table);
}

static inline int State_space_ta_Variable_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &State_space_ta_Variable_verify_table);
}

static inline int State_space_ta_Variable_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &State_space_ta_Variable_verify_table);
}

static int State_space_ta_State_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* location */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 1, 0, &State_space_ta_DBM_verify_table) /* clock_zone */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 2, 0, &State_space_ta_Variable_verify_table) /* var */)) return ret;
    return flatcc_verify_ok;
}

static inline int State_space_ta_State_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_State_identifier, &State_space_ta_State_verify_table);
}

static inline int State_space_ta_State_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_State_identifier, &State_space_ta_State_verify_table);
}

static inline int State_space_ta_State_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_State_type_identifier, &State_space_ta_State_verify_table);
}

static inline int State_space_ta_State_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_State_type_identifier, &State_space_ta_State_verify_table);
}

static inline int State_space_ta_State_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &State_space_ta_State_verify_table);
}

static inline int State_space_ta_State_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &State_space_ta_State_verify_table);
}

static inline int State_space_ta_State_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &State_space_ta_State_verify_table);
}

static inline int State_space_ta_State_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &State_space_ta_State_verify_table);
}

static int State_space_ta_State_transition_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* cible */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* action_id */)) return ret;
    return flatcc_verify_ok;
}

static inline int State_space_ta_State_transition_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_State_transition_identifier, &State_space_ta_State_transition_verify_table);
}

static inline int State_space_ta_State_transition_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_State_transition_identifier, &State_space_ta_State_transition_verify_table);
}

static inline int State_space_ta_State_transition_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_State_transition_type_identifier, &State_space_ta_State_transition_verify_table);
}

static inline int State_space_ta_State_transition_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_State_transition_type_identifier, &State_space_ta_State_transition_verify_table);
}

static inline int State_space_ta_State_transition_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &State_space_ta_State_transition_verify_table);
}

static inline int State_space_ta_State_transition_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &State_space_ta_State_transition_verify_table);
}

static inline int State_space_ta_State_transition_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &State_space_ta_State_transition_verify_table);
}

static inline int State_space_ta_State_transition_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &State_space_ta_State_transition_verify_table);
}

static int State_space_ta_State_transitions_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &State_space_ta_State_transition_verify_table) /* items */)) return ret;
    return flatcc_verify_ok;
}

static inline int State_space_ta_State_transitions_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_State_transitions_identifier, &State_space_ta_State_transitions_verify_table);
}

static inline int State_space_ta_State_transitions_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_State_transitions_identifier, &State_space_ta_State_transitions_verify_table);
}

static inline int State_space_ta_State_transitions_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_State_transitions_type_identifier, &State_space_ta_State_transitions_verify_table);
}

static inline int State_space_ta_State_transitions_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_State_transitions_type_identifier, &State_space_ta_State_transitions_verify_table);
}

static inline int State_space_ta_State_transitions_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &State_space_ta_State_transitions_verify_table);
}

static inline int State_space_ta_State_transitions_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &State_space_ta_State_transitions_verify_table);
}

static inline int State_space_ta_State_transitions_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &State_space_ta_State_transitions_verify_table);
}

static inline int State_space_ta_State_transitions_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &State_space_ta_State_transitions_verify_table);
}

static int State_space_ta_State_space_ta_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &State_space_ta_State_verify_table) /* etats */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &State_space_ta_State_transitions_verify_table) /* state_successors */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &State_space_ta_State_transitions_verify_table) /* state_predecessors */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 3, 0, 4, 4, INT64_C(1073741823)) /* nb_successors_by_state */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 4, 0, 4, 4, INT64_C(1073741823)) /* nb_predecessors_by_state */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 5, 0) /* locations */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 6, 0) /* actions */)) return ret;
    return flatcc_verify_ok;
}

static inline int State_space_ta_State_space_ta_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_State_space_ta_identifier, &State_space_ta_State_space_ta_verify_table);
}

static inline int State_space_ta_State_space_ta_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_State_space_ta_identifier, &State_space_ta_State_space_ta_verify_table);
}

static inline int State_space_ta_State_space_ta_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, State_space_ta_State_space_ta_type_identifier, &State_space_ta_State_space_ta_verify_table);
}

static inline int State_space_ta_State_space_ta_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, State_space_ta_State_space_ta_type_identifier, &State_space_ta_State_space_ta_verify_table);
}

static inline int State_space_ta_State_space_ta_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &State_space_ta_State_space_ta_verify_table);
}

static inline int State_space_ta_State_space_ta_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &State_space_ta_State_space_ta_verify_table);
}

static inline int State_space_ta_State_space_ta_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &State_space_ta_State_space_ta_verify_table);
}

static inline int State_space_ta_State_space_ta_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &State_space_ta_State_space_ta_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* STRUCTURE_STATE_SPACE_TA_VERIFIER_H */
