#ifndef STRUCTURE_STATE_SPACE_TA_BUILDER_H
#define STRUCTURE_STATE_SPACE_TA_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef STRUCTURE_STATE_SPACE_TA_READER_H
#include "structure_state_space_ta_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

static const flatbuffers_voffset_t __State_space_ta_DBM_required[] = { 0 };
typedef flatbuffers_ref_t State_space_ta_DBM_ref_t;
static State_space_ta_DBM_ref_t State_space_ta_DBM_clone(flatbuffers_builder_t *B, State_space_ta_DBM_table_t t);
__flatbuffers_build_table(flatbuffers_, State_space_ta_DBM, 2)

static const flatbuffers_voffset_t __State_space_ta_Variable_required[] = { 0 };
typedef flatbuffers_ref_t State_space_ta_Variable_ref_t;
static State_space_ta_Variable_ref_t State_space_ta_Variable_clone(flatbuffers_builder_t *B, State_space_ta_Variable_table_t t);
__flatbuffers_build_table(flatbuffers_, State_space_ta_Variable, 1)

static const flatbuffers_voffset_t __State_space_ta_State_required[] = { 0 };
typedef flatbuffers_ref_t State_space_ta_State_ref_t;
static State_space_ta_State_ref_t State_space_ta_State_clone(flatbuffers_builder_t *B, State_space_ta_State_table_t t);
__flatbuffers_build_table(flatbuffers_, State_space_ta_State, 3)

static const flatbuffers_voffset_t __State_space_ta_State_transition_required[] = { 0 };
typedef flatbuffers_ref_t State_space_ta_State_transition_ref_t;
static State_space_ta_State_transition_ref_t State_space_ta_State_transition_clone(flatbuffers_builder_t *B, State_space_ta_State_transition_table_t t);
__flatbuffers_build_table(flatbuffers_, State_space_ta_State_transition, 2)

static const flatbuffers_voffset_t __State_space_ta_State_transitions_required[] = { 0 };
typedef flatbuffers_ref_t State_space_ta_State_transitions_ref_t;
static State_space_ta_State_transitions_ref_t State_space_ta_State_transitions_clone(flatbuffers_builder_t *B, State_space_ta_State_transitions_table_t t);
__flatbuffers_build_table(flatbuffers_, State_space_ta_State_transitions, 1)

static const flatbuffers_voffset_t __State_space_ta_State_space_ta_required[] = { 0 };
typedef flatbuffers_ref_t State_space_ta_State_space_ta_ref_t;
static State_space_ta_State_space_ta_ref_t State_space_ta_State_space_ta_clone(flatbuffers_builder_t *B, State_space_ta_State_space_ta_table_t t);
__flatbuffers_build_table(flatbuffers_, State_space_ta_State_space_ta, 7)

#define __State_space_ta_DBM_formal_args , int32_t v0, flatbuffers_int32_vec_ref_t v1
#define __State_space_ta_DBM_call_args , v0, v1
static inline State_space_ta_DBM_ref_t State_space_ta_DBM_create(flatbuffers_builder_t *B __State_space_ta_DBM_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, State_space_ta_DBM, State_space_ta_DBM_file_identifier, State_space_ta_DBM_type_identifier)

#define __State_space_ta_Variable_formal_args , int32_t v0
#define __State_space_ta_Variable_call_args , v0
static inline State_space_ta_Variable_ref_t State_space_ta_Variable_create(flatbuffers_builder_t *B __State_space_ta_Variable_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, State_space_ta_Variable, State_space_ta_Variable_file_identifier, State_space_ta_Variable_type_identifier)

#define __State_space_ta_State_formal_args , int32_t v0, State_space_ta_DBM_ref_t v1, State_space_ta_Variable_ref_t v2
#define __State_space_ta_State_call_args , v0, v1, v2
static inline State_space_ta_State_ref_t State_space_ta_State_create(flatbuffers_builder_t *B __State_space_ta_State_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, State_space_ta_State, State_space_ta_State_file_identifier, State_space_ta_State_type_identifier)

#define __State_space_ta_State_transition_formal_args , int32_t v0, int32_t v1
#define __State_space_ta_State_transition_call_args , v0, v1
static inline State_space_ta_State_transition_ref_t State_space_ta_State_transition_create(flatbuffers_builder_t *B __State_space_ta_State_transition_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, State_space_ta_State_transition, State_space_ta_State_transition_file_identifier, State_space_ta_State_transition_type_identifier)

#define __State_space_ta_State_transitions_formal_args , State_space_ta_State_transition_vec_ref_t v0
#define __State_space_ta_State_transitions_call_args , v0
static inline State_space_ta_State_transitions_ref_t State_space_ta_State_transitions_create(flatbuffers_builder_t *B __State_space_ta_State_transitions_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, State_space_ta_State_transitions, State_space_ta_State_transitions_file_identifier, State_space_ta_State_transitions_type_identifier)

#define __State_space_ta_State_space_ta_formal_args ,\
  State_space_ta_State_vec_ref_t v0, State_space_ta_State_transitions_vec_ref_t v1, State_space_ta_State_transitions_vec_ref_t v2, flatbuffers_int32_vec_ref_t v3,\
  flatbuffers_int32_vec_ref_t v4, flatbuffers_string_vec_ref_t v5, flatbuffers_string_vec_ref_t v6
#define __State_space_ta_State_space_ta_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6
static inline State_space_ta_State_space_ta_ref_t State_space_ta_State_space_ta_create(flatbuffers_builder_t *B __State_space_ta_State_space_ta_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, State_space_ta_State_space_ta, State_space_ta_State_space_ta_file_identifier, State_space_ta_State_space_ta_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, State_space_ta_DBM_dim, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), State_space_ta_DBM)
__flatbuffers_build_vector_field(1, flatbuffers_, State_space_ta_DBM_matrice_applatie, flatbuffers_int32, int32_t, State_space_ta_DBM)

static inline State_space_ta_DBM_ref_t State_space_ta_DBM_create(flatbuffers_builder_t *B __State_space_ta_DBM_formal_args)
{
    if (State_space_ta_DBM_start(B)
        || State_space_ta_DBM_dim_add(B, v0)
        || State_space_ta_DBM_matrice_applatie_add(B, v1)) {
        return 0;
    }
    return State_space_ta_DBM_end(B);
}

static State_space_ta_DBM_ref_t State_space_ta_DBM_clone(flatbuffers_builder_t *B, State_space_ta_DBM_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (State_space_ta_DBM_start(B)
        || State_space_ta_DBM_dim_pick(B, t)
        || State_space_ta_DBM_matrice_applatie_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, State_space_ta_DBM_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, State_space_ta_Variable_v, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), State_space_ta_Variable)

static inline State_space_ta_Variable_ref_t State_space_ta_Variable_create(flatbuffers_builder_t *B __State_space_ta_Variable_formal_args)
{
    if (State_space_ta_Variable_start(B)
        || State_space_ta_Variable_v_add(B, v0)) {
        return 0;
    }
    return State_space_ta_Variable_end(B);
}

static State_space_ta_Variable_ref_t State_space_ta_Variable_clone(flatbuffers_builder_t *B, State_space_ta_Variable_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (State_space_ta_Variable_start(B)
        || State_space_ta_Variable_v_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, State_space_ta_Variable_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, State_space_ta_State_location, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), State_space_ta_State)
__flatbuffers_build_table_field(1, flatbuffers_, State_space_ta_State_clock_zone, State_space_ta_DBM, State_space_ta_State)
__flatbuffers_build_table_field(2, flatbuffers_, State_space_ta_State_var, State_space_ta_Variable, State_space_ta_State)

static inline State_space_ta_State_ref_t State_space_ta_State_create(flatbuffers_builder_t *B __State_space_ta_State_formal_args)
{
    if (State_space_ta_State_start(B)
        || State_space_ta_State_location_add(B, v0)
        || State_space_ta_State_clock_zone_add(B, v1)
        || State_space_ta_State_var_add(B, v2)) {
        return 0;
    }
    return State_space_ta_State_end(B);
}

static State_space_ta_State_ref_t State_space_ta_State_clone(flatbuffers_builder_t *B, State_space_ta_State_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (State_space_ta_State_start(B)
        || State_space_ta_State_location_pick(B, t)
        || State_space_ta_State_clock_zone_pick(B, t)
        || State_space_ta_State_var_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, State_space_ta_State_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, State_space_ta_State_transition_cible, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), State_space_ta_State_transition)
__flatbuffers_build_scalar_field(1, flatbuffers_, State_space_ta_State_transition_action_id, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), State_space_ta_State_transition)

static inline State_space_ta_State_transition_ref_t State_space_ta_State_transition_create(flatbuffers_builder_t *B __State_space_ta_State_transition_formal_args)
{
    if (State_space_ta_State_transition_start(B)
        || State_space_ta_State_transition_cible_add(B, v0)
        || State_space_ta_State_transition_action_id_add(B, v1)) {
        return 0;
    }
    return State_space_ta_State_transition_end(B);
}

static State_space_ta_State_transition_ref_t State_space_ta_State_transition_clone(flatbuffers_builder_t *B, State_space_ta_State_transition_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (State_space_ta_State_transition_start(B)
        || State_space_ta_State_transition_cible_pick(B, t)
        || State_space_ta_State_transition_action_id_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, State_space_ta_State_transition_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, State_space_ta_State_transitions_items, State_space_ta_State_transition, State_space_ta_State_transitions)

static inline State_space_ta_State_transitions_ref_t State_space_ta_State_transitions_create(flatbuffers_builder_t *B __State_space_ta_State_transitions_formal_args)
{
    if (State_space_ta_State_transitions_start(B)
        || State_space_ta_State_transitions_items_add(B, v0)) {
        return 0;
    }
    return State_space_ta_State_transitions_end(B);
}

static State_space_ta_State_transitions_ref_t State_space_ta_State_transitions_clone(flatbuffers_builder_t *B, State_space_ta_State_transitions_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (State_space_ta_State_transitions_start(B)
        || State_space_ta_State_transitions_items_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, State_space_ta_State_transitions_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, State_space_ta_State_space_ta_etats, State_space_ta_State, State_space_ta_State_space_ta)
__flatbuffers_build_table_vector_field(1, flatbuffers_, State_space_ta_State_space_ta_state_successors, State_space_ta_State_transitions, State_space_ta_State_space_ta)
__flatbuffers_build_table_vector_field(2, flatbuffers_, State_space_ta_State_space_ta_state_predecessors, State_space_ta_State_transitions, State_space_ta_State_space_ta)
__flatbuffers_build_vector_field(3, flatbuffers_, State_space_ta_State_space_ta_nb_successors_by_state, flatbuffers_int32, int32_t, State_space_ta_State_space_ta)
__flatbuffers_build_vector_field(4, flatbuffers_, State_space_ta_State_space_ta_nb_predecessors_by_state, flatbuffers_int32, int32_t, State_space_ta_State_space_ta)
__flatbuffers_build_string_vector_field(5, flatbuffers_, State_space_ta_State_space_ta_locations, State_space_ta_State_space_ta)
__flatbuffers_build_string_vector_field(6, flatbuffers_, State_space_ta_State_space_ta_actions, State_space_ta_State_space_ta)

static inline State_space_ta_State_space_ta_ref_t State_space_ta_State_space_ta_create(flatbuffers_builder_t *B __State_space_ta_State_space_ta_formal_args)
{
    if (State_space_ta_State_space_ta_start(B)
        || State_space_ta_State_space_ta_etats_add(B, v0)
        || State_space_ta_State_space_ta_state_successors_add(B, v1)
        || State_space_ta_State_space_ta_state_predecessors_add(B, v2)
        || State_space_ta_State_space_ta_nb_successors_by_state_add(B, v3)
        || State_space_ta_State_space_ta_nb_predecessors_by_state_add(B, v4)
        || State_space_ta_State_space_ta_locations_add(B, v5)
        || State_space_ta_State_space_ta_actions_add(B, v6)) {
        return 0;
    }
    return State_space_ta_State_space_ta_end(B);
}

static State_space_ta_State_space_ta_ref_t State_space_ta_State_space_ta_clone(flatbuffers_builder_t *B, State_space_ta_State_space_ta_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (State_space_ta_State_space_ta_start(B)
        || State_space_ta_State_space_ta_etats_pick(B, t)
        || State_space_ta_State_space_ta_state_successors_pick(B, t)
        || State_space_ta_State_space_ta_state_predecessors_pick(B, t)
        || State_space_ta_State_space_ta_nb_successors_by_state_pick(B, t)
        || State_space_ta_State_space_ta_nb_predecessors_by_state_pick(B, t)
        || State_space_ta_State_space_ta_locations_pick(B, t)
        || State_space_ta_State_space_ta_actions_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, State_space_ta_State_space_ta_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* STRUCTURE_STATE_SPACE_TA_BUILDER_H */
