namespace State_space_ta;

table DBM {
    dim:int;
    matrice_applatie:[int];
}

table Variable {
    v:int;
}

table State {
    location:int;
    clock_zone:DBM;
    var:Variable;
}

table State_transition {
    cible:int;
    action_id:int;
}

table State_transitions {
    items:[State_transition];
}

table State_space_ta {
    etats:[State];
    state_successors:[State_transitions];
    state_predecessors:[State_transitions];
    nb_successors_by_state:[int];
    nb_predecessors_by_state:[int];
    locations:[string];
    actions:[string];
}

root_type State_space_ta;