#ifndef STRUCTURE_STATE_SPACE_TA_READER_H
#define STRUCTURE_STATE_SPACE_TA_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct State_space_ta_DBM_table *State_space_ta_DBM_table_t;
typedef struct State_space_ta_DBM_table *State_space_ta_DBM_mutable_table_t;
typedef const flatbuffers_uoffset_t *State_space_ta_DBM_vec_t;
typedef flatbuffers_uoffset_t *State_space_ta_DBM_mutable_vec_t;
typedef const struct State_space_ta_Variable_table *State_space_ta_Variable_table_t;
typedef struct State_space_ta_Variable_table *State_space_ta_Variable_mutable_table_t;
typedef const flatbuffers_uoffset_t *State_space_ta_Variable_vec_t;
typedef flatbuffers_uoffset_t *State_space_ta_Variable_mutable_vec_t;
typedef const struct State_space_ta_State_table *State_space_ta_State_table_t;
typedef struct State_space_ta_State_table *State_space_ta_State_mutable_table_t;
typedef const flatbuffers_uoffset_t *State_space_ta_State_vec_t;
typedef flatbuffers_uoffset_t *State_space_ta_State_mutable_vec_t;
typedef const struct State_space_ta_State_transition_table *State_space_ta_State_transition_table_t;
typedef struct State_space_ta_State_transition_table *State_space_ta_State_transition_mutable_table_t;
typedef const flatbuffers_uoffset_t *State_space_ta_State_transition_vec_t;
typedef flatbuffers_uoffset_t *State_space_ta_State_transition_mutable_vec_t;
typedef const struct State_space_ta_State_transitions_table *State_space_ta_State_transitions_table_t;
typedef struct State_space_ta_State_transitions_table *State_space_ta_State_transitions_mutable_table_t;
typedef const flatbuffers_uoffset_t *State_space_ta_State_transitions_vec_t;
typedef flatbuffers_uoffset_t *State_space_ta_State_transitions_mutable_vec_t;
typedef const struct State_space_ta_State_space_ta_table *State_space_ta_State_space_ta_table_t;
typedef struct State_space_ta_State_space_ta_table *State_space_ta_State_space_ta_mutable_table_t;
typedef const flatbuffers_uoffset_t *State_space_ta_State_space_ta_vec_t;
typedef flatbuffers_uoffset_t *State_space_ta_State_space_ta_mutable_vec_t;
#ifndef State_space_ta_DBM_file_identifier
#define State_space_ta_DBM_file_identifier 0
#endif
/* deprecated, use State_space_ta_DBM_file_identifier */
#ifndef State_space_ta_DBM_identifier
#define State_space_ta_DBM_identifier 0
#endif
#define State_space_ta_DBM_type_hash ((flatbuffers_thash_t)0x74341128)
#define State_space_ta_DBM_type_identifier "\x28\x11\x34\x74"
#ifndef State_space_ta_DBM_file_extension
#define State_space_ta_DBM_file_extension "bin"
#endif
#ifndef State_space_ta_Variable_file_identifier
#define State_space_ta_Variable_file_identifier 0
#endif
/* deprecated, use State_space_ta_Variable_file_identifier */
#ifndef State_space_ta_Variable_identifier
#define State_space_ta_Variable_identifier 0
#endif
#define State_space_ta_Variable_type_hash ((flatbuffers_thash_t)0x4b6fe11f)
#define State_space_ta_Variable_type_identifier "\x1f\xe1\x6f\x4b"
#ifndef State_space_ta_Variable_file_extension
#define State_space_ta_Variable_file_extension "bin"
#endif
#ifndef State_space_ta_State_file_identifier
#define State_space_ta_State_file_identifier 0
#endif
/* deprecated, use State_space_ta_State_file_identifier */
#ifndef State_space_ta_State_identifier
#define State_space_ta_State_identifier 0
#endif
#define State_space_ta_State_type_hash ((flatbuffers_thash_t)0xb0f1ca4)
#define State_space_ta_State_type_identifier "\xa4\x1c\x0f\x0b"
#ifndef State_space_ta_State_file_extension
#define State_space_ta_State_file_extension "bin"
#endif
#ifndef State_space_ta_State_transition_file_identifier
#define State_space_ta_State_transition_file_identifier 0
#endif
/* deprecated, use State_space_ta_State_transition_file_identifier */
#ifndef State_space_ta_State_transition_identifier
#define State_space_ta_State_transition_identifier 0
#endif
#define State_space_ta_State_transition_type_hash ((flatbuffers_thash_t)0xab16b156)
#define State_space_ta_State_transition_type_identifier "\x56\xb1\x16\xab"
#ifndef State_space_ta_State_transition_file_extension
#define State_space_ta_State_transition_file_extension "bin"
#endif
#ifndef State_space_ta_State_transitions_file_identifier
#define State_space_ta_State_transitions_file_identifier 0
#endif
/* deprecated, use State_space_ta_State_transitions_file_identifier */
#ifndef State_space_ta_State_transitions_identifier
#define State_space_ta_State_transitions_identifier 0
#endif
#define State_space_ta_State_transitions_type_hash ((flatbuffers_thash_t)0x79b8dd3f)
#define State_space_ta_State_transitions_type_identifier "\x3f\xdd\xb8\x79"
#ifndef State_space_ta_State_transitions_file_extension
#define State_space_ta_State_transitions_file_extension "bin"
#endif
#ifndef State_space_ta_State_space_ta_file_identifier
#define State_space_ta_State_space_ta_file_identifier 0
#endif
/* deprecated, use State_space_ta_State_space_ta_file_identifier */
#ifndef State_space_ta_State_space_ta_identifier
#define State_space_ta_State_space_ta_identifier 0
#endif
#define State_space_ta_State_space_ta_type_hash ((flatbuffers_thash_t)0xfd2b6811)
#define State_space_ta_State_space_ta_type_identifier "\x11\x68\x2b\xfd"
#ifndef State_space_ta_State_space_ta_file_extension
#define State_space_ta_State_space_ta_file_extension "bin"
#endif



struct State_space_ta_DBM_table { uint8_t unused__; };

static inline size_t State_space_ta_DBM_vec_len(State_space_ta_DBM_vec_t vec)
__flatbuffers_vec_len(vec)
static inline State_space_ta_DBM_table_t State_space_ta_DBM_vec_at(State_space_ta_DBM_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(State_space_ta_DBM_table_t, vec, i, 0)
__flatbuffers_table_as_root(State_space_ta_DBM)

__flatbuffers_define_scalar_field(0, State_space_ta_DBM, dim, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_vector_field(1, State_space_ta_DBM, matrice_applatie, flatbuffers_int32_vec_t, 0)

struct State_space_ta_Variable_table { uint8_t unused__; };

static inline size_t State_space_ta_Variable_vec_len(State_space_ta_Variable_vec_t vec)
__flatbuffers_vec_len(vec)
static inline State_space_ta_Variable_table_t State_space_ta_Variable_vec_at(State_space_ta_Variable_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(State_space_ta_Variable_table_t, vec, i, 0)
__flatbuffers_table_as_root(State_space_ta_Variable)

__flatbuffers_define_scalar_field(0, State_space_ta_Variable, v, flatbuffers_int32, int32_t, INT32_C(0))

struct State_space_ta_State_table { uint8_t unused__; };

static inline size_t State_space_ta_State_vec_len(State_space_ta_State_vec_t vec)
__flatbuffers_vec_len(vec)
static inline State_space_ta_State_table_t State_space_ta_State_vec_at(State_space_ta_State_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(State_space_ta_State_table_t, vec, i, 0)
__flatbuffers_table_as_root(State_space_ta_State)

__flatbuffers_define_scalar_field(0, State_space_ta_State, location, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_table_field(1, State_space_ta_State, clock_zone, State_space_ta_DBM_table_t, 0)
__flatbuffers_define_table_field(2, State_space_ta_State, var, State_space_ta_Variable_table_t, 0)

struct State_space_ta_State_transition_table { uint8_t unused__; };

static inline size_t State_space_ta_State_transition_vec_len(State_space_ta_State_transition_vec_t vec)
__flatbuffers_vec_len(vec)
static inline State_space_ta_State_transition_table_t State_space_ta_State_transition_vec_at(State_space_ta_State_transition_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(State_space_ta_State_transition_table_t, vec, i, 0)
__flatbuffers_table_as_root(State_space_ta_State_transition)

__flatbuffers_define_scalar_field(0, State_space_ta_State_transition, cible, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(1, State_space_ta_State_transition, action_id, flatbuffers_int32, int32_t, INT32_C(0))

struct State_space_ta_State_transitions_table { uint8_t unused__; };

static inline size_t State_space_ta_State_transitions_vec_len(State_space_ta_State_transitions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline State_space_ta_State_transitions_table_t State_space_ta_State_transitions_vec_at(State_space_ta_State_transitions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(State_space_ta_State_transitions_table_t, vec, i, 0)
__flatbuffers_table_as_root(State_space_ta_State_transitions)

__flatbuffers_define_vector_field(0, State_space_ta_State_transitions, items, State_space_ta_State_transition_vec_t, 0)

struct State_space_ta_State_space_ta_table { uint8_t unused__; };

static inline size_t State_space_ta_State_space_ta_vec_len(State_space_ta_State_space_ta_vec_t vec)
__flatbuffers_vec_len(vec)
static inline State_space_ta_State_space_ta_table_t State_space_ta_State_space_ta_vec_at(State_space_ta_State_space_ta_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(State_space_ta_State_space_ta_table_t, vec, i, 0)
__flatbuffers_table_as_root(State_space_ta_State_space_ta)

__flatbuffers_define_vector_field(0, State_space_ta_State_space_ta, etats, State_space_ta_State_vec_t, 0)
__flatbuffers_define_vector_field(1, State_space_ta_State_space_ta, state_successors, State_space_ta_State_transitions_vec_t, 0)
__flatbuffers_define_vector_field(2, State_space_ta_State_space_ta, state_predecessors, State_space_ta_State_transitions_vec_t, 0)
__flatbuffers_define_vector_field(3, State_space_ta_State_space_ta, nb_successors_by_state, flatbuffers_int32_vec_t, 0)
__flatbuffers_define_vector_field(4, State_space_ta_State_space_ta, nb_predecessors_by_state, flatbuffers_int32_vec_t, 0)
__flatbuffers_define_vector_field(5, State_space_ta_State_space_ta, locations, flatbuffers_string_vec_t, 0)
__flatbuffers_define_vector_field(6, State_space_ta_State_space_ta, actions, flatbuffers_string_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* STRUCTURE_STATE_SPACE_TA_READER_H */
