# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State_space_ta

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DBM(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DBM()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDBM(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DBM
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DBM
    def Dim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DBM
    def MatriceApplatie(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # DBM
    def MatriceApplatieAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # DBM
    def MatriceApplatieLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DBM
    def MatriceApplatieIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def DBMStart(builder):
    builder.StartObject(2)

def Start(builder):
    DBMStart(builder)

def DBMAddDim(builder, dim):
    builder.PrependInt32Slot(0, dim, 0)

def AddDim(builder, dim):
    DBMAddDim(builder, dim)

def DBMAddMatriceApplatie(builder, matriceApplatie):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(matriceApplatie), 0)

def AddMatriceApplatie(builder, matriceApplatie):
    DBMAddMatriceApplatie(builder, matriceApplatie)

def DBMStartMatriceApplatieVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMatriceApplatieVector(builder, numElems):
    return DBMStartMatriceApplatieVector(builder, numElems)

def DBMEnd(builder):
    return builder.EndObject()

def End(builder):
    return DBMEnd(builder)
