# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State_space_ta

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class State(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = State()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # State
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # State
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # State
    def ClockZone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from State_space_ta.DBM import DBM
            obj = DBM()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State
    def Var(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from State_space_ta.Variable import Variable
            obj = Variable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def StateStart(builder):
    builder.StartObject(3)

def Start(builder):
    StateStart(builder)

def StateAddLocation(builder, location):
    builder.PrependInt32Slot(0, location, 0)

def AddLocation(builder, location):
    StateAddLocation(builder, location)

def StateAddClockZone(builder, clockZone):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(clockZone), 0)

def AddClockZone(builder, clockZone):
    StateAddClockZone(builder, clockZone)

def StateAddVar(builder, var):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(var), 0)

def AddVar(builder, var):
    StateAddVar(builder, var)

def StateEnd(builder):
    return builder.EndObject()

def End(builder):
    return StateEnd(builder)
