# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State_space_ta

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class State_space_ta(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = State_space_ta()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsState_space_ta(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # State_space_ta
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # State_space_ta
    def Etats(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from State_space_ta.State import State
            obj = State()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_space_ta
    def EtatsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # State_space_ta
    def EtatsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # State_space_ta
    def StateSuccessors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from State_space_ta.State_transitions import State_transitions
            obj = State_transitions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_space_ta
    def StateSuccessorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # State_space_ta
    def StateSuccessorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # State_space_ta
    def StatePredecessors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from State_space_ta.State_transitions import State_transitions
            obj = State_transitions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_space_ta
    def StatePredecessorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # State_space_ta
    def StatePredecessorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # State_space_ta
    def NbSuccessorsByState(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # State_space_ta
    def NbSuccessorsByStateAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # State_space_ta
    def NbSuccessorsByStateLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # State_space_ta
    def NbSuccessorsByStateIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # State_space_ta
    def NbPredecessorsByState(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # State_space_ta
    def NbPredecessorsByStateAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # State_space_ta
    def NbPredecessorsByStateLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # State_space_ta
    def NbPredecessorsByStateIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # State_space_ta
    def Locations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # State_space_ta
    def LocationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # State_space_ta
    def LocationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # State_space_ta
    def Actions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # State_space_ta
    def ActionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # State_space_ta
    def ActionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def State_space_taStart(builder):
    builder.StartObject(7)

def Start(builder):
    State_space_taStart(builder)

def State_space_taAddEtats(builder, etats):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(etats), 0)

def AddEtats(builder, etats):
    State_space_taAddEtats(builder, etats)

def State_space_taStartEtatsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEtatsVector(builder, numElems):
    return State_space_taStartEtatsVector(builder, numElems)

def State_space_taAddStateSuccessors(builder, stateSuccessors):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(stateSuccessors), 0)

def AddStateSuccessors(builder, stateSuccessors):
    State_space_taAddStateSuccessors(builder, stateSuccessors)

def State_space_taStartStateSuccessorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStateSuccessorsVector(builder, numElems):
    return State_space_taStartStateSuccessorsVector(builder, numElems)

def State_space_taAddStatePredecessors(builder, statePredecessors):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(statePredecessors), 0)

def AddStatePredecessors(builder, statePredecessors):
    State_space_taAddStatePredecessors(builder, statePredecessors)

def State_space_taStartStatePredecessorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStatePredecessorsVector(builder, numElems):
    return State_space_taStartStatePredecessorsVector(builder, numElems)

def State_space_taAddNbSuccessorsByState(builder, nbSuccessorsByState):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(nbSuccessorsByState), 0)

def AddNbSuccessorsByState(builder, nbSuccessorsByState):
    State_space_taAddNbSuccessorsByState(builder, nbSuccessorsByState)

def State_space_taStartNbSuccessorsByStateVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNbSuccessorsByStateVector(builder, numElems):
    return State_space_taStartNbSuccessorsByStateVector(builder, numElems)

def State_space_taAddNbPredecessorsByState(builder, nbPredecessorsByState):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(nbPredecessorsByState), 0)

def AddNbPredecessorsByState(builder, nbPredecessorsByState):
    State_space_taAddNbPredecessorsByState(builder, nbPredecessorsByState)

def State_space_taStartNbPredecessorsByStateVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNbPredecessorsByStateVector(builder, numElems):
    return State_space_taStartNbPredecessorsByStateVector(builder, numElems)

def State_space_taAddLocations(builder, locations):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(locations), 0)

def AddLocations(builder, locations):
    State_space_taAddLocations(builder, locations)

def State_space_taStartLocationsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLocationsVector(builder, numElems):
    return State_space_taStartLocationsVector(builder, numElems)

def State_space_taAddActions(builder, actions):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(actions), 0)

def AddActions(builder, actions):
    State_space_taAddActions(builder, actions)

def State_space_taStartActionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActionsVector(builder, numElems):
    return State_space_taStartActionsVector(builder, numElems)

def State_space_taEnd(builder):
    return builder.EndObject()

def End(builder):
    return State_space_taEnd(builder)
