# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State_space_ta

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class State_transition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = State_transition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsState_transition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # State_transition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # State_transition
    def Cible(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # State_transition
    def ActionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def State_transitionStart(builder):
    builder.StartObject(2)

def Start(builder):
    State_transitionStart(builder)

def State_transitionAddCible(builder, cible):
    builder.PrependInt32Slot(0, cible, 0)

def AddCible(builder, cible):
    State_transitionAddCible(builder, cible)

def State_transitionAddActionId(builder, actionId):
    builder.PrependInt32Slot(1, actionId, 0)

def AddActionId(builder, actionId):
    State_transitionAddActionId(builder, actionId)

def State_transitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return State_transitionEnd(builder)
