# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State_space_ta

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class State_transitions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = State_transitions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsState_transitions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # State_transitions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # State_transitions
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from State_space_ta.State_transition import State_transition
            obj = State_transition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_transitions
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # State_transitions
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def State_transitionsStart(builder):
    builder.StartObject(1)

def Start(builder):
    State_transitionsStart(builder)

def State_transitionsAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def AddItems(builder, items):
    State_transitionsAddItems(builder, items)

def State_transitionsStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemsVector(builder, numElems):
    return State_transitionsStartItemsVector(builder, numElems)

def State_transitionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return State_transitionsEnd(builder)
