# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State_space_ta

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Variable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Variable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Variable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Variable
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def VariableStart(builder):
    builder.StartObject(1)

def Start(builder):
    VariableStart(builder)

def VariableAddV(builder, v):
    builder.PrependInt32Slot(0, v, 0)

def AddV(builder, v):
    VariableAddV(builder, v)

def VariableEnd(builder):
    return builder.EndObject()

def End(builder):
    return VariableEnd(builder)
